### ISSUE TITLE
Zedstar

### ISSUE THREAD

**Issue by xDidntPot** [HorizonPE/HorizonCore#1]
LMAO @Zedstar16!

**Comment by xDidntPot** [comment]
hi @Zedstar16

**Comment by xDidntPot** [comment]
looks like this didnt end well huh

**Comment by xDidntPot** [comment]
smh

**Comment by Zedstar16** [comment]
> looks like this didnt end well huh

yeah kinda um got forgotten about 2 years ago

**Comment by xDidntPot** [comment]
lol

**Comment by xDidntPot** [comment]
so uh whens the online time update?!?!

**Comment by xDidntPot** [comment]
i need it for my pocketmine-mp server! I can't live without it on my pocketmine-mp server!

**Comment by xDidntPot** [comment]
i guess dragonfly is just superior
